# Uncomment the next line to define a global platform for your project
platform :ios, "9.0"

def pods
  pod "Bolts"
  pod "FBSDKCoreKit", "4.22.1"
  pod "FBSDKShareKit", "4.22.1"
  pod "FBSDKLoginKit", "4.22.1"
  pod "IQKeyboardManager"
  pod "Firebase"
  pod "Firebase/Core"
  pod "Firebase/Auth"
  pod "Firebase/Crash"
  pod "Firebase/Database"
  pod "Firebase/Messaging"
  pod "Firebase/RemoteConfig"
  pod "Firebase/Storage"

  rn_path = "../node_modules/react-native"
  rn_maps_path = "../node_modules/react-native-maps"

 # pod "yoga", path: "#{rn_path}/ReactCommon/yoga"
 # pod "React", path: rn_path, subspecs: [
 #   "Core",
 #   "RCTActionSheet",
 #   "RCTAnimation",
 #   "RCTGeolocation",
 #   "RCTImage",
 #   "RCTLinkingIOS",
 #   "RCTNetwork",
 #   "RCTSettings",
 #   "RCTText",
 #   "RCTVibration",
 #   "RCTWebSocket",
 #   "DevSupport"
 # ]

 # pod "react-native-maps", path: rn_maps_path
end

def message_signer_pods
  pod "Alamofire"
end

target "MudamosMobile" do
  # Uncomment the next line if you"re using Swift or would like to use dynamic frameworks
  use_frameworks!

  pods

  target "MudamosMobileTests" do
    inherit! :search_paths
    # Pods for testing
  end

end

target "MudamosMobileTagviewBeta" do
  use_frameworks!

  pods
end

target "MudamosProduction" do
  use_frameworks!

  pods
end

target "MessageSignerAction" do
  use_frameworks!

  message_signer_pods
end

target "MessageSignerActionBeta" do
  use_frameworks!

  message_signer_pods
end

target "MessageSignerActionProduction" do
  use_frameworks!

  message_signer_pods
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    if target.name == "react-native-google-maps"
#      puts "Disabling CLANG_ENABLE_MODULES for target: #{target}"
#
#      target.build_configurations.each do |config|
#        config.build_settings["CLANG_ENABLE_MODULES"] = "No"
#      end
#    end
#
#    if target.name == "React"
#      puts "Removing React target"
#      target.remove_from_project
#    end
#  end
#end
