# Uncomment the next line to define a global platform for your project
platform :ios, "9.0"

def pods
  pod "Bolts"
  pod "FBSDKCoreKit"
  pod "FBSDKShareKit"
  pod "FBSDKLoginKit"
  pod "IQKeyboardManager"
  pod "Firebase"
  pod "Firebase/Core"
  pod "Firebase/Auth"
  pod "Firebase/Crash"
  pod "Firebase/Database"
  pod "Firebase/Messaging"
  pod "Firebase/RemoteConfig"
  pod "Firebase/Storage"
end

target "MudamosMobile" do
  # Uncomment the next line if you"re using Swift or would like to use dynamic frameworks
  use_frameworks!

  pods

  target "MudamosMobileTests" do
    inherit! :search_paths
    # Pods for testing
  end

end

target "MudamosMobileTagviewBeta" do
  use_frameworks!

  pods
end

target "MudamosProduction" do
  use_frameworks!

  pods
end

target "MessageSignerActionBeta" do
  use_frameworks!
end
