# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MessageSignerAction' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MessageSignerAction

end

target 'MessageSignerActionBeta' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MessageSignerActionBeta

end

target 'MessageSignerActionProduction' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MessageSignerActionProduction

end

target 'MudamosMobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MudamosMobile

  target 'MudamosMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MudamosMobileTagviewBeta' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MudamosMobileTagviewBeta

end

target 'MudamosProduction' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MudamosProduction

end
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

[
  'Firebase',
  'Firebase/Core',
  'Firebase/Auth',
  'Firebase/Storage',
  'Firebase/Database',
  'Firebase/RemoteConfig',
  'Firebase/Messaging'
].each do |lib|
  pod lib
end
